### ISSUE TITLE
Can I use number for defaultCountry?

### ISSUE THREAD

**Issue by alatebloomer** [patw0929/react-intl-tel-input#154]
Can I use number for defaultCountry?

For example, I put '1' or '+01' for defaultCountry, and the deafult will be usa.

**Comment by eggman64** [comment]
Probably not, because +1 is also the dial code for Canada :)

**Comment by patw0929** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/patw0929/react-intl-tel-input/releases) and then please use the [issue template](https://raw.githubusercontent.com/patw0929/react-intl-tel-input/master/.github/ISSUE_TEMPLATE.md). You can also contribute directly by providing a patch. :)

Thank you!
