### ISSUE TITLE
Basic Usage does not work

### ISSUE THREAD

**Issue by ajbraus** [patw0929/react-intl-tel-input#200]
This plugin (and all of these react int tel plugins) really have a problem. They are not modular and depend on webpack unnecessarily. The whole point of react is to include all styles and functionality IN THE COMPONENT. 

Anyways it doesn't work.

**Comment by patw0929** [comment]
Could you provide your code and more information about the not working issue? Maybe it's some webpack setting or something wrong.
I made a [demo](https://7zovk74zx.codesandbox.io/) on codesandbox based on react-intl-tel-input v5.0.1 for testing, it is working.

Thanks.

**Comment by patw0929** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/patw0929/react-intl-tel-input/releases) and then please use the [issue template](https://raw.githubusercontent.com/patw0929/react-intl-tel-input/master/.github/ISSUE_TEMPLATE.md). You can also contribute directly by providing a patch. :)

Thank you!
