### ISSUE TITLE
Vietnamese phone number with new prefixes are not supported

### ISSUE THREAD

**Issue by Bunthai** [patw0929/react-intl-tel-input#288]
Vietnamese mobile carriers have rolled out new prefixes ([Reference](https://en.nhandan.org.vn/scitech/item/6614602-vietnamese-mobile-carriers-roll-out-new-prefixes.html)).

Currently, the library works well with the old prefix of Vietnamese phone numbers but does not work with the new prefix ones

For example, it says this phone number 01671234567 (old prefix) is valid, but it says this phone number 0371234567 (new prefix) is invalid.

Please kindly provide me some solutions what I should do to make it support both the old and the new prefixes.

**Comment by Bunthai** [comment]
**The issue is fixed.**

After I am trying to upgrade the library to the latest version (7.0.1) and remove the import of libphonenumber from my component, it works well with the Vietnamese phone numbers with new prefixes.

**Comment by m-nathani** [comment]
Hi guys.. 

I updated to the lastest version (7.1.0) as mentioned above and it worked for the new vietnams prefix, However i want to support both the old and the new prefix formats. How should i support both the format.

Please let me know how do to that? Currently the whole application is stop/bugged due to this in veitnam.

**Comment by AllStackDev1** [comment]
Isn't there a way to manually do this, like pass it as a props array of countries new prefix, bcos Nigeria number with 090 or 091 are marked as invalid
