### ISSUE TITLE
Using With Create-React-App

### ISSUE THREAD

**Issue by Westernwells** [patw0929/react-intl-tel-input#325]
I was not able to use this to work with CRA. please can you write a note on how to use with create react app. 
## Steps to Reproduce

1.
2.
3.
4.

Code:

```js
```

## Environment

* Version:
  
* Browser:

**Comment by mcataford** [comment]
Hi @Westernwells!

Adding documentation is a good idea! Can you talk a bit about how you've set up your app?

I'm going to revise the documentation / try it out shortly so we can compare notes and fill in gaps.

**Comment by mcataford** [comment]
Quick follow-up: turns out some sass files were exported instead of the usual compiled css. #328 addresses it and is currently being released as a patch release. As such, `8.0.1` should fix your issue.

I'd still love to hear how your set up your app, but the general steps should go as follows:

- <CRA usual setup>
- Import the default import to get the input component (`import IntlTelInput from 'react-intel-tel-input`)
- Import the default stylesheet (`import react-intl-tel-input/dist/main.css`) or your own into your app (if you are using your own and are using a SASS file instead, you'd need `node-sass` to be installed as well, but only if you use something more than just plain CSS)
- `yarn start`

I ran through these steps with a dummy CRA and a hand-packed `8.0.1` and it worked just fine. If you have a more complex setup, do let me know and I'll see how we can bridge the gap and get you rolling. :rocket:

**Comment by Westernwells** [comment]
i got it working. please if possible there should documentation for how to handle the onPhoneNumberchange prop. i later figure it out that it return an arrays that need to be destructured.

**Comment by mcataford** [comment]
Duly noted! Thanks for the feedback! I'll follow-up with more detailed component API documentation this week. 👍
