### ISSUE TITLE
Can't load file

### ISSUE THREAD

**Issue by cagarweyne** [patw0929/react-intl-tel-input#97]
I am getting an error with the line `import 'file?name=libphonenumber.js!./node_modules/react-intl-tel-input/dist/libphonenumber.js';` throws an error: `bundle.js:68 Uncaught Error: Cannot find module "file?name=libphonenumber.js!./node_modules/react-intl-tel-input/dist/libphonenumber.js"`

**Comment by brunops** [comment]
Where are you requiring it from?

Note that this `import` has a relative path to `node_modules` folder, so `./node_modules/react-intl...` will work if your file is in the root folder, otherwise you might need to fix the path.

If you're requiring it from `src/index.js`, your import would be `../node_modules/react-intl...`, if you're requiring it from `src/foo/index.js`, your import would be `../../node_modules/react-intl...`

**Comment by cagarweyne** [comment]
I've added the file using the correct path, but without the `file?name=libphonenumber.js!` bit. Why is this bit needed? When I put this in it throws the same error regardless of the path given. Also, I can't seem to be able to load the css file either, so I have loaded this file in directly into my index.html page.

**Comment by cagarweyne** [comment]
OK, I've fixed the issue with loading the file. I didn't have `file?name=libphonenumber.js!` bit - it kept throwing error.
